#
# continuous integration workflow
#
name: build repo

on:
 push:
    branches: [ master]
 pull_request:
    branches: [ master]
 workflow_dispatch:
    branches: [ master]

jobs:
  build_ros2:
    uses: ros-event-camera/ros-build-action/.github/workflows/build_ros2.yml@master
    with:
      repo: ${{ github.event.repository.name }}
